language: go
sudo: false
install: true
go:
  - 1.6.3
  - 1.7rc5
  - tip
script:
  - ./go.test.bash
services:
  - mongodb
matrix:
  allow_failures:
    - go: tip
after_success:
  - bash <(curl -s https://codecov.io/bash)
