language: go
sudo: false
install: true
go:
  - 1.5.4
  - 1.6.3
  - 1.7rc2
  - tip
env:
  global:
    - GO15VENDOREXPERIMENT=1
script: make test
services:
  - mongodb
matrix:
  allow_failures:
    - go: tip
